Try to solve error
/home/hip/git/mechble/mechanical-blender/source/blender/editors/mesh/editmesh_select.c: In function ‘EDBM_select_pick’:
/home/hip/git/mechble/mechanical-blender/source/blender/blenlib/BLI_compiler_typecheck.h:177:18: error: ‘_Generic’ selector of type ‘BMGeom * {aka struct BMGeom *}’ is not compatible with any association
  ((void)_Generic((v), a0: 0, b0: 0, c0: 0, d0: 0, e0: 0, f0: 0, g0: 0, h0: 0, i0: 0, j0: 0, k0: 0, l0: 0, m0: 0, \

probably because of  (__STDC_VERSION__ >= 201112L)